### ISSUE TITLE
Question about preprocess bbox by CLIP image encoder

### ISSUE THREAD

**Issue by BossunWang** [Johnathan-Xie/ZSD-YOLO#4]
Hi expert,
I would like to know the detail about generating lable.pt.
Whether to resize bbox to CLIP assigned image size(ex: 224*224) directly or padding for keeping ratio and then resize ?

**Comment by Johnathan-Xie** [comment]
Thank you for your interest in our work.

We used direct resizing to 224x224 as if I remember correctly the padding of objects led to poor embeddings. Also, I believe the original CLIP was trained using center crop + resize.

Also, I have now pushed a new commit that shows the data processing notebooks. See https://github.com/Johnathan-Xie/ZSD-YOLO/issues/3 for more information.
